<?php  ?>
<ul id="sidebar" style="color:red">
            <li><a href="Ali.html">Ao no Exorcist</a></li>
            <li><a href="Ali.html">Attack on titan</a></li>
            <li><a href="Ali.html">Bakuman</a></li>
            <li><a href="Ali.html">Durarara</a></li>
            <li><a href="Ali.html">Fairy Tail</a></li>
            <li><a href="Ali.html">Hellsing</a></li>
            <li><a href="Ali.html">Hetalia</a></li>
            <li><a href="Ali.html">K-On!</a></li>
            <li><a href="Ali.html">Madoka Magica</a></li>
            <li><a href="Ali.html">Pandora Hearts</a></li>
            <li><a href="Ali.html">Ranma</a></li>
            <li><a href="Ali.html">Shougo Chara</a></li>
            <li><a href="Ali.html">Soul Eater</a></li>
            <li><a href="Ali.html">Vampire Knight</a></li>
            <li><a href="Ali.html">Vocaloid</a></li>
            <li><a href="Ali.html">Amnesia</a></li>
            <li><a href="Ali.html">Magi</a></li>
            <li><a href="Ali.html">Date-A-Live</a></li>
            <li><a href="Ali.html">Assassins Creed</a></li>
            <li><a href="Ali.html">Free!</a></li>
            <li><a href="Ali.html">Inu X Boku SS</a></li>
            <li><a href="Ali.html">Accel World</a></li>
            <li><a href="Ali.html">Future Diary</a></li>
            <li><a href="Ali.html">Beelzebub</a></li>
            <li><a href="Ali.html">Angel Beats!</a></li>
            <li><a href="Ali.html">Kuroko No Baskue</a></li>
            <li><a href="Ali.html">Final Fantasy</a></li>
            <li><a href="Ali.html">League Of Legends</a></li>
            <li><a href="Ali.html">Sword Art Online</a></li>
            <li><a href="Ali.html">Angel Sanctuary</a></li>
            <li><a href="Ali.html">Black Cat</a></li>
            <li><a href="Ali.html">Bleach</a></li>
            <li><a href="Ali.html">One Piece</a></li>
            <li><a href="Ali.html">Chobits</a></li>
            <li><a href="Ali.html">Claymore</a></li>
            <li><a href="Ali.html">D. Gray-Man</a></li>
            <li><a href="Ali.html">Death Note</a></li>
            <li><a href="Ali.html">Detective Conan</a></li>
            <li><a href="Ali.html">Dragon Ball Z</a></li>
            <li><a href="Ali.html">Fate/Stay Night</a></li>
            <li><a href="Ali.html">Fruits Basket</a></li>
            <li><a href="Ali.html">Fullmetal Alchemist Brotherhood</a></li>
            <li><a href="Ali.html">Code Geass</a></li>
            <li><a href="Ali.html">Gundam</a></li>
            <li><a href="Ali.html">Hitman Reborn</a></li>
            <li><a href="Ali.html">Ouran Highschool Host Club</a></li>
            <li><a href="Ali.html">Inuyasha</a></li>
            <li><a href="Ali.html">Kingdom Hearts</a></li>
            <li><a href="Ali.html">Black Butler</a></li>
            <li><a href="Ali.html">Loveless</a></li>
            <li><a href="Ali.html">Lucky Star</a></li>
            <li><a href="Ali.html">Nana</a></li>
            <li><a href="Ali.html">Naruto</a></li>
            <li><a href="Ali.html">One Piece</a></li>
            <li><a href="Ali.html">Onegai Sensei</a></li>
            <li><a href="Ali.html">Parasyte</a></li>
            <li><a href="Ali.html">Rosario Vampire</a></li>
            <li><a href="Ali.html">The Melancholy Of Haruhi Susumiya</a></li>
            <li><a href="Ali.html">Guily Crown</a></li>
            <li><a href="Ali.html">Dangan-Ronpa</a></li>
            <li><a href="Ali.html">Legend Of Zelda</a></li>
            <li><a href="Ali.html">Rurouni Kenshin</a></li>
            <li><a href="Ali.html">Sailor Moon (Crystal)</a></li>
            <li><a href="Ali.html">Spirited Away</a></li>
            <li><a href="Ali.html">Totoro</a></li>
            <li><a href="Ali.html">Prince Of Tennis</a></li>
            <li><a href="Ali.html">Trinity Blood</a></li>
            <li><a href="Ali.html">Yu Yu Hakusho</a></li>
            <li><a href="Ali.html">Pokemon</a></li>
            <li><a href="Ali.html">Akame Ga Kill</a></li>
            <li><a href="Ali.html">K.</a></li>
            <li><a href="Ali.html">Tokyo Ghoul</a></li>
            <li><a href="Ali.html">No Game No Life</a></li>
            <li><a href="Ali.html">My Little Pony</a></li>
      </ul>
      <?php  ?>